#!/usr/bin/env bash
# =============================================================================
# yuleASR Release Script
# =============================================================================
# Creates a signed, checksummed release tag from a clean working tree.
#
# Usage:
#   tools/release/release.sh [major|minor|patch|<explicit-version>]
#   tools/release/release.sh --dry-run patch
#
# Steps:
#   1. Validate working tree is clean
#   2. Compute next semver (or use explicit version)
#   3. Run full build + test suite
#   4. Create annotated (optionally GPG-signed) tag
#   5. Generate SHA256 manifest for release artifacts
#   6. Print push instructions
#
# Environment:
#   GPG_KEY_ID   — optional, GPG key for signing (default: git signingkey)
#   SKIP_TESTS   — set to "1" to skip test suite (not recommended)
#   DRY_RUN      — set to "1" or pass --dry-run
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[RELEASE]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*" >&2; }

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
    shift
fi

# ---------------------------------------------------------------------------
# 1. Validate working tree
# ---------------------------------------------------------------------------
if [[ -n "$(git status --porcelain)" ]]; then
    err "Working tree is not clean. Commit or stash changes first."
    git status --short
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. Compute version
# ---------------------------------------------------------------------------
BUMP="${1:-}"

get_latest_tag() {
    git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0"
}

parse_semver() {
    local tag="$1"
    tag="${tag#v}"
    echo "$tag" | sed 's/^v//' | tr '.' '\n'
}

LATEST_TAG=$(get_latest_tag)
read -r MAJOR MINOR PATCH <<< "$(parse_semver "$LATEST_TAG" | tr '\n' ' ')"
MAJOR="${MAJOR:-0}"
MINOR="${MINOR:-0}"
PATCH="${PATCH:-0}"

case "$BUMP" in
    major)
        MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
    minor)
        MINOR=$((MINOR + 1)); PATCH=0 ;;
    patch|"")
        PATCH=$((PATCH + 1)) ;;
    v*.*.*|*.*.*)
        VERSION="${BUMP#v}"
        read -r MAJOR MINOR PATCH <<< "$(echo "$VERSION" | tr '.' ' ')"
        ;;
    *)
        err "Unknown version spec: $BUMP"
        echo "Usage: $0 [major|minor|patch|<version>]"
        exit 1 ;;
esac

VERSION="${MAJOR}.${MINOR}.${PATCH}"
TAG="v${VERSION}"

log "Latest tag:  $LATEST_TAG"
log "New version: $TAG"

if git rev-parse "$TAG" >/dev/null 2>&1; then
    err "Tag $TAG already exists"
    exit 1
fi

if [[ $DRY_RUN -eq 1 ]]; then
    log "[DRY RUN] Would create tag $TAG"
    exit 0
fi

# ---------------------------------------------------------------------------
# 3. Run tests
# ---------------------------------------------------------------------------
if [[ "${SKIP_TESTS:-0}" != "1" ]]; then
    log "Running build + test suite..."
    BUILD_DIR="build-release"
    cmake -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release 2>&1 | tail -5
    cmake --build "$BUILD_DIR" -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu)" 2>&1 | tail -5
    ctest --test-dir "$BUILD_DIR" --output-on-failure 2>&1 | tail -10
    log "Tests passed"
else
    warn "Skipping tests (SKIP_TESTS=1)"
fi

# ---------------------------------------------------------------------------
# 4. Create tag
# ---------------------------------------------------------------------------
GPG_KEY="${GPG_KEY_ID:-$(git config --get user.signingkey 2>/dev/null || echo "")}"

RELEASE_NOTES="Release $TAG

Generated by tools/release/release.sh
Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Commit: $(git rev-parse --short HEAD)"

if [[ -n "$GPG_KEY" ]] && command -v gpg >/dev/null 2>&1; then
    log "Creating GPG-signed tag $TAG"
    git tag -s "$TAG" -m "$RELEASE_NOTES" -u "$GPG_KEY" 2>/dev/null || {
        warn "GPG signing failed, creating annotated tag instead"
        git tag -a "$TAG" -m "$RELEASE_NOTES"
    }
else
    log "Creating annotated tag $TAG (no GPG key configured)"
    git tag -a "$TAG" -m "$RELEASE_NOTES"
fi

# ---------------------------------------------------------------------------
# 5. Generate SHA256 manifest
# ---------------------------------------------------------------------------
MANIFEST="release-${VERSION}-SHA256.txt"
log "Generating SHA256 manifest: $MANIFEST"

{
    echo "# yuleASR $VERSION SHA256 Checksums"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Commit:    $(git rev-parse HEAD)"
    echo "#"

    if [[ -d "$BUILD_DIR" ]]; then
        find "$BUILD_DIR" -maxdepth 3 \( -name '*.elf' -o -name '*.hex' -o -name '*.bin' -o -name '*.a' \) -print0 |
            while IFS= read -r -d '' f; do
                sha256sum "$f" 2>/dev/null || shasum -a 256 "$f"
            done
    fi

    echo "# Source archive:"
    git archive --format=tar.gz --prefix="yuleasr-${VERSION}/" -o "/tmp/yuleasr-${VERSION}.tar.gz" HEAD 2>/dev/null && {
        sha256sum "/tmp/yuleasr-${VERSION}.tar.gz" 2>/dev/null || shasum -a 256 "/tmp/yuleasr-${VERSION}.tar.gz"
        rm -f "/tmp/yuleasr-${VERSION}.tar.gz"
    }
} > "$MANIFEST"

if [[ -s "$MANIFEST" ]]; then
    log "Manifest written: $MANIFEST"
else
    warn "No binary artifacts found; manifest contains source archive only"
    {
        echo "# yuleASR $VERSION SHA256 Checksums"
        echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# Commit:    $(git rev-parse HEAD)"
    } > "$MANIFEST"
fi

# ---------------------------------------------------------------------------
# 6. Instructions
# ---------------------------------------------------------------------------
echo ""
log "=== Release $TAG created ==="
echo ""
echo "Tag:       $TAG"
echo "Manifest:  $MANIFEST"
echo ""
echo "To push:"
echo "  git push origin $TAG"
echo ""
echo "To push with manifest:"
echo "  git push origin $TAG"
echo "  # Upload $MANIFEST to GitHub Releases"
echo ""
echo "To verify the tag:"
echo "  git tag -v $TAG"
