/*==================================================================================================
* Project              : YuleTech AutoSAR BSW
* Platform             : NXP i.MX8M Mini
* Dependencies         : ...
*
* Copyright (c) 2026 Shanghai Yule Electronics Technology Co., Ltd.
* All rights reserved.
*
* SPDX-License-Identifier: MIT
*
* @file Fls_MemMap.h
* @brief Fls memory mapping
*================================================================================================*/

/*==================================================================================================
 *                              FLS MEMORY MAPPING HEADER
 *==================================================================================================
 * This is a simplified memory mapping header for Fls module.
 * In production, this would be generated by the configuration tool.
 *==================================================================================================
 */

#ifndef FLS_MEMMAP_H
#define FLS_MEMMAP_H

/* Prevent double definition of memory mapping macros */
#ifdef FLS_START_SEC_CODE
    #undef FLS_START_SEC_CODE
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_STOP_SEC_CODE
    #undef FLS_STOP_SEC_CODE
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef FLS_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef FLS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_START_SEC_VAR_INIT_UNSPECIFIED
    #undef FLS_START_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_START_SEC_CONST_UNSPECIFIED
    #undef FLS_START_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef FLS_STOP_SEC_CONST_UNSPECIFIED
    #undef FLS_STOP_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

/* For this implementation, memory sections are handled by the compiler/linker */

#endif /* FLS_MEMMAP_H */
