/*==================================================================================================
* Project              : YuleTech AutoSAR BSW
* Platform             : NXP i.MX8M Mini
* Dependencies         : ...
*
* Copyright (c) 2026 Shanghai Yule Electronics Technology Co., Ltd.
* All rights reserved.
*
* SPDX-License-Identifier: MIT
*
* @file Det_MemMap.h
* @brief Det memory mapping
*================================================================================================*/

/*==================================================================================================
 *                              DET MEMORY MAPPING HEADER
 *==================================================================================================
 * This is a simplified memory mapping header for Det module.
 * In production, this would be generated by the configuration tool.
 *==================================================================================================
 */

#ifndef DET_MEMMAP_H
#define DET_MEMMAP_H

/* Prevent double definition of memory mapping macros */
#ifdef DET_START_SEC_CODE
    #undef DET_START_SEC_CODE
    #undef MEMMAP_ERROR
#endif

#ifdef DET_STOP_SEC_CODE
    #undef DET_STOP_SEC_CODE
    #undef MEMMAP_ERROR
#endif

#ifdef DET_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef DET_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef DET_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef DET_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef DET_START_SEC_VAR_INIT_UNSPECIFIED
    #undef DET_START_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef DET_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef DET_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef DET_START_SEC_CONST_UNSPECIFIED
    #undef DET_START_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

#ifdef DET_STOP_SEC_CONST_UNSPECIFIED
    #undef DET_STOP_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR
#endif

/* For this implementation, memory sections are handled by the compiler/linker */
/* No special pragmas needed for simplified implementation */

#endif /* DET_MEMMAP_H */
