/**
 * @file SecOC_Cfg.h
 * @brief SecOC Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SECOC_CFG_H
#define SECOC_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SECOC_DEV_ERROR_DETECT    STD_ON
#define SECOC_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define SECOC_NUM_TX_PDUS    (4U)
#define SECOC_NUM_RX_PDUS    (4U)
#define SECOC_VERIFICATION_RETRY_COUNT    (3U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define SECOC_MAIN_FUNCTION_PERIOD_RX_MS    (10U)
#define SECOC_MAIN_FUNCTION_PERIOD_TX_MS    (10U)
#define SECOC_TX_PDU_ID_0    (0U)
#define SECOC_TX_PDU_ID_1    (1U)
#define SECOC_TX_PDU_ID_2    (2U)
#define SECOC_TX_PDU_ID_3    (3U)
#define SECOC_RX_PDU_ID_0    (0U)
#define SECOC_RX_PDU_ID_1    (1U)
#define SECOC_RX_PDU_ID_2    (2U)
#define SECOC_RX_PDU_ID_3    (3U)
#define SECOC_FRESHNESS_VALUE_TX_LENGTH    (16U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SECOC_VERIFICATION_TIMEOUT_MS    (100U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SECOC_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define SECOC_CFG_AR_RELEASE_MINOR_VERSION    (7U)
#define SECOC_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define SECOC_CFG_SW_MAJOR_VERSION    (1U)
#define SECOC_CFG_SW_MINOR_VERSION    (0U)
#define SECOC_CFG_SW_PATCH_VERSION    (0U)
#define SECOC_MAX_PDU_LENGTH    (256U)
#define SECOC_AUTH_ALGORITHM    SECOC_HMAC_SHA256
#define SECOC_AUTH_INFO_LENGTH    (16U)
#define SECOC_FRESHNESS_VALUE_TYPE    SECOC_COUNTER
#define SECOC_FRESHNESS_VALUE_LENGTH    (32U)
#define SECOC_DATA_ID_LENGTH    (1U)
#define SECOC_MAX_FRESHNESS_VALUE    (4294967295U)
#define SECOC_FRESHNESS_RESET_THRESHOLD    (4026531840U)
#define SECOC_ENABLE_FRESHNESS_SYNC    STD_ON
#define SECOC_ENABLE_FRESHNESS_PERSISTENCE    STD_ON
#define SECOC_NVM_BLOCK_FRESHNESS    (8U)
#define SECOC_OVERRIDE_STATUS_ALLOWED    STD_ON
#define SECOC_DEFAULT_VERIFICATION_STATUS    SECOC_UNVERIFIED
#define SECOC_CSM_JOB_ID_AUTH    CSM_JOB_ID_MAC_GENERATE_1
#define SECOC_CSM_JOB_ID_VERIFY    CSM_JOB_ID_MAC_VERIFY_1
#define SECOC_MAX_CRYPTO_OPERATIONS    (4U)
#ifndef SECOC_AUTH_LENGTH_4
#define SECOC_AUTH_LENGTH_4    (4U)
#endif
#ifndef SECOC_AUTH_LENGTH_8
#define SECOC_AUTH_LENGTH_8    (8U)
#endif
#ifndef SECOC_FRESHNESS_LENGTH_3
#define SECOC_FRESHNESS_LENGTH_3    (3U)
#endif
#ifndef SECOC_FRESHNESS_LENGTH_4
#define SECOC_FRESHNESS_LENGTH_4    (4U)
#endif
#ifndef SECOC_MAX_PDUS
#define SECOC_MAX_PDUS    (4U)
#endif

#endif /* SECOC_CFG_H */

/*==================[end of file]===========================================*/
